### ISSUE TITLE
[editor]: Support c in preview

### ISSUE THREAD

**Issue by Kiamehr5** [AdamRaichu/vscode-zip-viewer#104]
Please add support for `.c` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by Kiamehr5** [comment]
NO REOPEN IT BRO

**Comment by AdamRaichu** [comment]
> NO REOPEN IT BRO

I added it to the preview.... Make sure you are using version `3.15.2` or later. If you are still having trouble, send me a screenshot.

![image](https://github.com/AdamRaichu/vscode-zip-viewer/assets/91494019/66d42270-02ee-4a52-8ac2-8eb5e912bb0d)

**Comment by Kiamehr5** [comment]
oh yeah now it works... but anyway before i recived a error message regarding so. Thanks
