### ISSUE TITLE
bug: false alerts about Script injections

### ISSUE THREAD

**Issue by KluSe** [AdamRaichu/vscode-zip-viewer#118]
**Describe the bug**
The warning about a `</style>` tag in the additionalCSS property is shown every time the extension is used, even if the property is not set in either user settings or workspace settings.

**To Reproduce**

1. ensure the `zipViewer.ZipEdit.additionalCSS` property is not set in the user `settings.json` or the workspace `settings.json`.
2. open a zip file using the Zip Viewer Editor.

**Expected behavior**
No error message should be shown.

**Environment**
What type of VS Code were you using when you encountered the problem?

Mac OS Sonoma 14.5
Visual Studio Code Version: 1.91.0
Zip Tools v3.17.0

**Comment by KluSe** [comment]
Taking a quick look, this seems to be the issue:

https://github.com/AdamRaichu/vscode-zip-viewer/blob/64b380d0c37c70b5364dbf486ec0071d59215806/src/ZipEdit.js#L56-L63

The warning should be inside the if condition.

**Comment by AdamRaichu** [comment]
*heavy face palm*

I'll get that fixed immediately, and sorry for the delay, I was taking a break this month.

**Comment by AdamRaichu** [comment]
Well I thought I fixed this, but apparently not....

**Comment by AdamRaichu** [comment]
Sorry for the extra notification. I actually did fix it, I just had the test line in my user settings.
