### ISSUE TITLE
[Feature] Suggested file extension: pbit and pbix

### ISSUE THREAD

**Issue by Konshus1** [AdamRaichu/vscode-zip-viewer#12]
### Suggested file extension

.pbit

**Comment by AdamRaichu** [comment]
Thank you for posting an issue! I will add this and publish immediately.

**Comment by Konshus1** [comment]
Wow, that was superfast and I had trouble using the interface.  Also, .pbix files are the same thing as pbit files and are just zip files with a different file extension.

**Comment by AdamRaichu** [comment]
Thanks for the heads up about pbix! I saw that at fileinfo.com.

Could you explain a bit more what you meant when you said you had trouble using the interface? Was it...

- It was hard to figure out how to add a custom file extension to settings.
- It was hard to use the command to open the pbit/pbix files.
- Or something else?

**Comment by Konshus1** [comment]
When I went to add the extension, the bottom link for documentation was disabled for me and I wasn't able to post the documentation link about pbit files.

**Comment by AdamRaichu** [comment]
Ah. That is an empty slot for you to paste a link to help me out when I add more. It was ok here because I was able to find it myself.

![image](https://user-images.githubusercontent.com/91494019/211652850-d45cef09-47da-47b9-a60b-78da6a4ca1e1.png)

You could have pasted in this link. https://fileinfo.com/extension/pbit

**Comment by AdamRaichu** [comment]
Feature is going through automatic checks, should be live soon (extension version `2.3.2`).

**Comment by AdamRaichu** [comment]
If this extension has been helpful to you, please consider [leaving a review](https://marketplace.visualstudio.com/items?itemName=AdamRaichu.zip-viewer&ssr=false#review-details). I would really appreciate it.
