### ISSUE TITLE
[editor]: Support xls in preview

### ISSUE THREAD

**Issue by Tvkoushik** [AdamRaichu/vscode-zip-viewer#125]
Please add support for `.xls` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
Hey, I can't find a clear answer to what file format an xls file is. Could you upload an example one for me @Tvkoushik?

**Comment by Tvkoushik** [comment]
@AdamRaichu .xls is the older version of Microsoft Excel's (.xlsx) format that was used during 1997 to 2004. Attached a copy for your reference
[detail.xls](https://github.com/user-attachments/files/16693025/detail.xls)

**Comment by AdamRaichu** [comment]
> @AdamRaichu .xls is the older version of Microsoft Excel's (.xlsx) format that was used during 1997 to 2004. Attached a copy for your reference [detail.xls](https://github.com/user-attachments/files/16693025/detail.xls)

I was able to figure that part out, but wasn't able to get a clear answer on whether it was text or binary. I can now see that's it is indeed a text file, and so will add it to the list. You should get a release within 15 minutes.
