### ISSUE TITLE
[editor]: Support mtx in preview

### ISSUE THREAD

**Issue by NadmanKhan** [AdamRaichu/vscode-zip-viewer#131]
Please add support for `.mtx` files to the editor preview.

A `.mtx` file is a [Matrix Market file format](https://en.wikipedia.org/wiki/Matrix_Market_exchange_formats) [standardized by the NIST](https://math.nist.gov/MatrixMarket/formats.html#MMformat). Such files are often used in research domains related to numerical analysis.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
Will be merged and published as soon as CI finishes. 

Thank you for providing the extra information! That makes my job a lot easier.
