### ISSUE TITLE
[editor]: Support ultraman bot/User_db/Plans/737622248269152396 in preview

### ISSUE THREAD

**Issue by HSSonly** [AdamRaichu/vscode-zip-viewer#24]
Please add support for `.ultraman bot/User_db/Plans/737622248269152396` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
Could you link to an example of this file please? Or perhaps what "ultraman bot" is?

Also, I'm not sure I will be able to support this kind of file (as my setup is currently) as the file name didn't have a recognizable file extension.

**Comment by HSSonly** [comment]
[{
	"resource": "/d:/ultraman bot/.venv/Lib/site-packages/pip/_vendor/rich/jupyter.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports",
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"ipython.display\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 89,
	"startColumn": 14,
	"endLineNumber": 89,
	"endColumn": 29
}]

**Comment by AdamRaichu** [comment]
Sorry, but the file does not have a proper file extension and so I cannot add it to the preview as my code is written. However, see #25 for a possible future solution.
