### ISSUE TITLE
bug: Zip creation doesn't include recursive contents

### ISSUE THREAD

**Issue by rlayers** [AdamRaichu/vscode-zip-viewer#26]
**Describe the bug**
Zipping a folder doesn't include recursive contents (i.e., subfolders and their associated files/folders are not included.)

**To Reproduce**

1. Create a project with a subfolder that contains a file and one subfolder that also contains a file
2. Right click click and select "Zip tools: create a zip file from folder"
3. The produced zip-file does not include the subfolder and subfile

**Expected behavior**
Zipping a folder should include all contents - including subfolders.

**Environment**
Git-hub web-version of vscode

**Comment by AdamRaichu** [comment]
Could you link to an example repo that demonstrates this please?

**Comment by rlayers** [comment]
I was using the extension to zip this folder:

https://github.com/rlayers/pawpaw/tree/master/pawpaw

Here is some more info that may be helpful:

1. After zipping, if I left click on the created .zip file in vscode (web version), I can see a full, recursive list of everything.  So this seems good, however...

2. If I right click on the created .zip file and select "download", the downloaded .zip file only contains the top-most folder level files.  I.e., subfolders (and their contents) are not present in the downloaded file.

**Comment by AdamRaichu** [comment]
I can confirm the issue exists. I have maybe one or two ideas of places to look for the problem, but I am surprised by this bug as it seems rather unusual.

I am taking a week off from coding starting tomorrow, and so it will be a bit before I can do in depth testing/debugging; I apologize for the inconvenience.

Until then, you will have to download the folder to your device and zip it locally. Again, sorry for the inconvenience.

**Comment by AdamRaichu** [comment]
Thank you so much for reporting this bug. It has been fixed as of `v3.5.0`.
