### ISSUE TITLE
[Feature] Suggested file extension: .msi & .nba

### ISSUE THREAD

**Issue by erenerturk1** [AdamRaichu/vscode-zip-viewer#48]
### Suggested file extension

.msi and .nba

### Documentation

https://fileinfo.com/extension/msi & https://fileinfo.com/extension/nba

**Comment by AdamRaichu** [comment]
I see that `.nba` files are listed as zip format. 👍🏻 However, `.msi` is listed as "binary" which is not necessarily zip format. Could you confirm for me that `msi` is in fact zip format?

**Comment by AdamRaichu** [comment]
So I downloaded the node.js `msi` installer, renamed it to `.zip`, and tried to open it with windows file explorer. No dice 😕. It appears to be compressed with 7-zip, which is not currently supported by the extension.

See #49 for future updates.

**Comment by erenerturk1** [comment]
Sorry, I only checked with 7-zip. You could still add .nba though.

**Comment by AdamRaichu** [comment]
> Sorry, I only checked with 7-zip. You could still add .nba though.

I did in the code, but then forgot to publish it (oops). Doing that now.
