### ISSUE TITLE
[editor]: Support pkl in preview

### ISSUE THREAD

**Issue by bhanudamera** [AdamRaichu/vscode-zip-viewer#61]
Please add support for `.pkl` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
Sorry, but it does not appear (according to fileinfo.com) that pkl files are text files.

> A PKL file is a file created by pickle, a [Python](https://techterms.com/definition/python) module that enables objects to be serialized to files on disk and deserialized back into the program at runtime. It contains a byte stream that represents the objects.
