### ISSUE TITLE
[editor]: Support cpgz in preview

### ISSUE THREAD

**Issue by Renee-1717** [AdamRaichu/vscode-zip-viewer#82]
Please add support for `.cpgz` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
Could you explain this format a bit better? It seems only to be for corrupt zip files.... Obviously if it is corrupt I would have no way of displaying it properly.

**Comment by Renee-1717** [comment]
Muchas gracias por su comentario, ya lo arregle, si era un documento corrupto, gracias amigo, realmente lo aprecio

**Comment by AdamRaichu** [comment]
De nada! Encantado de ayudarte.
