### ISSUE TITLE
feat: create of zip workspace on commit

### ISSUE THREAD

**Issue by ecxod** [AdamRaichu/vscode-zip-viewer#90]
**Is your feature request related to a problem? Please describe.**
Your plugin could be useful for people who write Firefox add-ons, as the add-ons are simple zip files called "xpi".

**Describe the solution you'd like**
it would be great to have a button to zip the whole workspace and place the **__project__.xpi** file next to it. Something like a "commit hook", each time I commit, the plugin updates the xpi file.

Do it !  ;-)

**Comment by AdamRaichu** [comment]
I have added `.xpi` to to the extensions list. The rest of your suggestion (running actions on commit) is not ready yet, but I will take a look at it.

**Comment by AdamRaichu** [comment]
Required issues to fix before this can be implemented:

- [ ] #43

**Comment by AdamRaichu** [comment]
Actually now that I think about it, I think that something like this is out of scope for this extension, because it won't work for the web.
