### ISSUE TITLE
+[editor]: Support jar in preview

### ISSUE THREAD

**Issue by KingNucifera** [AdamRaichu/vscode-zip-viewer#97]
Please add support for `.jar` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by KavyanshKhaitan2** [comment]
Should be as simple as the `.zip` preview, since in reality, `.jar` files are just glorified `.zip` files.

**Comment by AdamRaichu** [comment]
Sorry for such a late response, and for the negative response, but...

Duplicate of #46.

> Sorry, but I don't plan to support previewing zip files inside of zip files. Instead, use the [selective extraction](https://github.com/AdamRaichu/vscode-zip-viewer#selective-extraction) feature to extract the zip you want to preview, then open it normally.
